ARG NODE_VERSION=24.18.0

FROM node:${NODE_VERSION}-alpine AS builder
WORKDIR /app

COPY package*.json ./
RUN npm ci

COPY . .
RUN npm run build

FROM nginx:1.30-alpine-slim

RUN cp /etc/nginx/nginx.conf /tmp/nginx.conf.docker-original

RUN apk update && apk upgrade --no-cache \
    && rm -rf /var/cache/apk/*

RUN cp /tmp/nginx.conf.docker-original /etc/nginx/nginx.conf \
    && rm /tmp/nginx.conf.docker-original

RUN apk add --no-cache libcap \
    && setcap 'cap_net_bind_service=+ep' /usr/sbin/nginx

COPY --from=builder /app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf

RUN chown -R nginx:nginx /var/cache/nginx \
    && chown -R nginx:nginx /var/log/nginx \
    && chown -R nginx:nginx /etc/nginx/conf.d \
    && touch /var/run/nginx.pid \
    && chown -R nginx:nginx /var/run/nginx.pid

EXPOSE 8080 8443

USER nginx

CMD ["nginx", "-g", "daemon off;"]