ARG NODE_VERSION=24.18.0
FROM node:${NODE_VERSION}-alpine AS builder
WORKDIR /app

COPY package*.json ./
RUN npm ci

COPY . .
RUN npm run build

FROM nginx:1.30-alpine-slim AS base

RUN cp /etc/nginx/nginx.conf /tmp/nginx.conf.docker-original

RUN apk update && apk upgrade --no-cache \
    && rm -rf /var/cache/apk/*

RUN cp /tmp/nginx.conf.docker-original /etc/nginx/nginx.conf \
    && rm /tmp/nginx.conf.docker-original

FROM base
COPY --from=builder /app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]