services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: edgeucate-server
    restart: unless-stopped
    ports:
      - "4200:4200"
    env_file:
      - .env
    volumes:
      - ./server:/app
      - /app/node_modules

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: edgeucate-client
    restart: unless-stopped
    ports:
      - "5173:5173"
    env_file:
      - .env
    volumes:
      - ./client/src:/app/src
      - ./client/public:/app/public
      - ./client/index.html:/app/index.html
      - ./client/vite.config.ts:/app/vite.config.ts
    depends_on:
      - server