ARG NODE_VERSION=24.18.0
FROM node:${NODE_VERSION}-alpine
WORKDIR /app

RUN apk add --no-cache wget

COPY package*.json ./
RUN chown -R node:node /app

USER node
RUN npm install && npm cache clean --force

COPY --chown=node:node . .

EXPOSE 4200
CMD ["npm", "run", "start:dev"]
