ARG NODE_VERSION=24.18.0
FROM node:${NODE_VERSION}-alpine AS builder
WORKDIR /app

COPY package*.json ./

RUN npm ci
COPY . .
RUN npm run build

RUN npm prune --production && npm cache clean --force

FROM node:${NODE_VERSION}-alpine AS runner
WORKDIR /app

RUN apk update && apk upgrade --no-cache \
    && rm -rf /usr/local/lib/node_modules/npm \
    && rm -rf /usr/local/bin/npm \
    && rm -rf /usr/local/bin/npx \
    && rm -rf /root/.npm \
    && rm -rf /tmp/*

RUN chown -R node:node /app
USER node

COPY --from=builder --chown=node:node /app/dist ./dist
COPY --from=builder --chown=node:node /app/node_modules ./node_modules
COPY --from=builder --chown=node:node /app/package.json ./

EXPOSE 4200
CMD ["node", "dist/main"]